/* ============================================================
   ProtoMacro — foods-db.js
   Curated local food database. Mix of USDA FoodData Central
   values and researched cultural cuisine averages (per 100g).
   Values are cooked weights where applicable. `tags` power the
   relevance scorer so e.g. "chicken" matches "Chicken breast".
   ============================================================ */

const RAW_FOODS = [

  /* ========== BANGLADESHI / SOUTH ASIAN ========== */
  { name: 'Rice, white Bangladeshi (cooked)', calories: 130, protein: 2.7, carbs: 28,   fat: 0.3,  tags: ['rice','bhaat','bangladeshi','south asian'] },
  { name: 'Rice, parboiled (cooked)',         calories: 128, protein: 2.6, carbs: 28,   fat: 0.3,  tags: ['rice','seddho','bangladeshi'] },
  { name: 'Ruti / Chapati',                   calories: 297, protein: 9,   carbs: 55,   fat: 3.7,  tags: ['ruti','chapati','roti','bread','bangladeshi','indian'] },
  { name: 'Paratha (plain)',                  calories: 326, protein: 7,   carbs: 45,   fat: 14,   tags: ['paratha','bread','bangladeshi','indian'] },
  { name: 'Naan bread',                       calories: 310, protein: 9,   carbs: 55,   fat: 7,    tags: ['naan','bread','indian','bangladeshi'] },
  { name: 'Puri (fried bread)',               calories: 340, protein: 7,   carbs: 45,   fat: 15,   tags: ['puri','luchi','bread','fried','bangladeshi','indian'] },
  { name: 'Dal, red lentil (cooked)',         calories: 116, protein: 9,   carbs: 20,   fat: 0.4,  tags: ['dal','daal','lentil','masoor','bangladeshi','indian'] },
  { name: 'Dal, yellow moong (cooked)',       calories: 105, protein: 7,   carbs: 18,   fat: 0.4,  tags: ['dal','moong','mung','bangladeshi','indian'] },
  { name: 'Dal, chana (cooked)',              calories: 164, protein: 9,   carbs: 27,   fat: 2.6,  tags: ['dal','chana','chickpea','bangladeshi','indian'] },
  { name: 'Hilsa fish (cooked)',              calories: 273, protein: 22,  carbs: 0,    fat: 20,   tags: ['hilsa','ilish','fish','bangladeshi'] },
  { name: 'Rohu fish (cooked)',               calories: 97,  protein: 17,  carbs: 0,    fat: 2.7,  tags: ['rohu','fish','bangladeshi','indian'] },
  { name: 'Catla fish (cooked)',              calories: 111, protein: 19,  carbs: 0,    fat: 3.5,  tags: ['catla','fish','bangladeshi'] },
  { name: 'Pangas fish (cooked)',             calories: 88,  protein: 15,  carbs: 0,    fat: 2.8,  tags: ['pangas','pangasius','fish','bangladeshi'] },
  { name: 'Prawn / Chingri (cooked)',         calories: 99,  protein: 24,  carbs: 0,    fat: 0.3,  tags: ['prawn','chingri','shrimp','seafood','bangladeshi'] },
  { name: 'Beef curry (cooked)',              calories: 185, protein: 21,  carbs: 4,    fat: 9,    tags: ['beef','curry','meat','bangladeshi','indian'] },
  { name: 'Mutton curry (cooked)',            calories: 225, protein: 20,  carbs: 3,    fat: 15,   tags: ['mutton','goat','curry','meat','bangladeshi','indian'] },
  { name: 'Chicken curry (cooked)',           calories: 175, protein: 20,  carbs: 4,    fat: 9,    tags: ['chicken','curry','meat','bangladeshi','indian'] },
  { name: 'Egg curry',                        calories: 160, protein: 11,  carbs: 5,    fat: 11,   tags: ['egg','curry','bangladeshi','indian'] },
  { name: 'Biryani, chicken',                 calories: 190, protein: 12,  carbs: 22,   fat: 6,    tags: ['biryani','chicken','rice','bangladeshi','indian'] },
  { name: 'Biryani, mutton',                  calories: 220, protein: 13,  carbs: 22,   fat: 9,    tags: ['biryani','mutton','rice','bangladeshi','indian'] },
  { name: 'Khichuri',                         calories: 130, protein: 5,   carbs: 22,   fat: 3,    tags: ['khichuri','khichdi','rice','lentil','bangladeshi','indian'] },
  { name: 'Halwa, suji',                      calories: 280, protein: 4,   carbs: 45,   fat: 10,   tags: ['halwa','suji','semolina','dessert','bangladeshi','indian'] },
  { name: 'Payesh / Kheer',                   calories: 150, protein: 4,   carbs: 25,   fat: 4,    tags: ['payesh','kheer','rice','pudding','dessert','bangladeshi','indian'] },
  { name: 'Mishti doi (sweet yogurt)',        calories: 140, protein: 4,   carbs: 24,   fat: 3,    tags: ['mishti','doi','yogurt','sweet','dessert','bangladeshi'] },
  { name: 'Rasgulla',                         calories: 186, protein: 4,   carbs: 37,   fat: 3,    tags: ['rasgulla','sweet','dessert','bangladeshi','indian'] },
  { name: 'Jalebi',                           calories: 370, protein: 2,   carbs: 68,   fat: 10,   tags: ['jalebi','sweet','dessert','bangladeshi','indian'] },
  { name: 'Singara / Samosa',                 calories: 262, protein: 4,   carbs: 30,   fat: 14,   tags: ['singara','samosa','snack','bangladeshi','indian'] },
  { name: 'Piyaju (lentil fritter)',          calories: 220, protein: 8,   carbs: 25,   fat: 10,   tags: ['piyaju','fritter','snack','bangladeshi'] },
  { name: 'Beguni (eggplant fritter)',        calories: 180, protein: 3,   carbs: 22,   fat: 9,    tags: ['beguni','eggplant','fritter','snack','bangladeshi'] },
  { name: 'Aloo bhaji (potato stir fry)',     calories: 130, protein: 2,   carbs: 18,   fat: 6,    tags: ['aloo','potato','bhaji','bangladeshi','indian'] },
  { name: 'Shorshe ilish (mustard hilsa)',    calories: 290, protein: 22,  carbs: 3,    fat: 21,   tags: ['hilsa','ilish','mustard','shorshe','fish','bangladeshi'] },
  { name: 'Bitter gourd / Karela',            calories: 17,  protein: 1,   carbs: 3.7,  fat: 0.2,  tags: ['bitter','gourd','karela','uchhe','vegetable','bangladeshi','indian'] },
  { name: 'Jackfruit, ripe',                  calories: 95,  protein: 1.7, carbs: 23,   fat: 0.6,  tags: ['jackfruit','kathal','fruit','bangladeshi','indian'] },
  { name: 'Jackfruit, young (cooked)',        calories: 98,  protein: 1.5, carbs: 22,   fat: 0.3,  tags: ['jackfruit','echor','vegetable','bangladeshi'] },
  { name: 'Mustard oil',                      calories: 884, protein: 0,   carbs: 0,    fat: 100,  tags: ['mustard','oil','fat','bangladeshi','indian'] },
  { name: 'Ghee',                             calories: 900, protein: 0,   carbs: 0,    fat: 100,  tags: ['ghee','fat','oil','bangladeshi','indian'] },

  /* ========== INDIAN ========== */
  { name: 'Idli',                             calories: 58,  protein: 2,   carbs: 12,   fat: 0.4,  tags: ['idli','rice','south indian','indian'] },
  { name: 'Dosa (plain)',                     calories: 133, protein: 3.5, carbs: 22,   fat: 3.7,  tags: ['dosa','south indian','indian'] },
  { name: 'Sambar',                           calories: 55,  protein: 3,   carbs: 8,    fat: 1.5,  tags: ['sambar','lentil','south indian','indian'] },
  { name: 'Palak paneer',                     calories: 180, protein: 10,  carbs: 7,    fat: 13,   tags: ['palak','paneer','spinach','indian'] },
  { name: 'Paneer',                           calories: 265, protein: 18,  carbs: 3.4,  fat: 20,   tags: ['paneer','cheese','indian','vegetarian'] },
  { name: 'Butter chicken (murgh makhani)',   calories: 200, protein: 19,  carbs: 6,    fat: 11,   tags: ['butter','chicken','murgh','makhani','indian'] },
  { name: 'Tandoori chicken',                 calories: 162, protein: 25,  carbs: 3,    fat: 6,    tags: ['tandoori','chicken','indian'] },
  { name: 'Chicken tikka masala',             calories: 195, protein: 21,  carbs: 8,    fat: 9,    tags: ['tikka','masala','chicken','indian'] },
  { name: 'Rajma (kidney bean curry)',        calories: 140, protein: 8,   carbs: 22,   fat: 2.5,  tags: ['rajma','kidney','bean','curry','indian'] },
  { name: 'Chole / Chana masala',             calories: 168, protein: 9,   carbs: 26,   fat: 4,    tags: ['chole','chana','chickpea','masala','indian'] },
  { name: 'Aloo gobi',                        calories: 95,  protein: 3,   carbs: 14,   fat: 4,    tags: ['aloo','gobi','potato','cauliflower','indian'] },
  { name: 'Saag aloo',                        calories: 110, protein: 3,   carbs: 15,   fat: 5,    tags: ['saag','aloo','spinach','potato','indian'] },
  { name: 'Matar paneer',                     calories: 170, protein: 8,   carbs: 10,   fat: 11,   tags: ['matar','paneer','peas','indian'] },
  { name: 'Dal makhani',                      calories: 150, protein: 8,   carbs: 18,   fat: 5,    tags: ['dal','makhani','lentil','indian'] },
  { name: 'Upma',                             calories: 148, protein: 3.5, carbs: 25,   fat: 4,    tags: ['upma','semolina','breakfast','indian'] },
  { name: 'Poha',                             calories: 130, protein: 2.5, carbs: 24,   fat: 3,    tags: ['poha','rice','flattened','breakfast','indian'] },
  { name: 'Vada pav',                         calories: 290, protein: 6,   carbs: 40,   fat: 12,   tags: ['vada','pav','street food','indian'] },
  { name: 'Pani puri / Golgappa',             calories: 180, protein: 3,   carbs: 28,   fat: 6,    tags: ['pani','puri','golgappa','street food','indian'] },
  { name: 'Lassi (plain)',                    calories: 70,  protein: 3.5, carbs: 8,    fat: 2.5,  tags: ['lassi','drink','yogurt','indian'] },
  { name: 'Mango lassi',                      calories: 120, protein: 3,   carbs: 20,   fat: 2.5,  tags: ['mango','lassi','drink','indian'] },
  { name: 'Masala chai (with milk & sugar)',  calories: 60,  protein: 2,   carbs: 8,    fat: 2,    tags: ['chai','tea','masala','drink','indian'] },
  { name: 'Gulab jamun',                      calories: 175, protein: 3,   carbs: 30,   fat: 5,    tags: ['gulab','jamun','dessert','sweet','indian'] },
  { name: 'Barfi / Burfi',                    calories: 370, protein: 8,   carbs: 55,   fat: 14,   tags: ['barfi','burfi','dessert','sweet','indian'] },
  { name: 'Ladoo, besan',                     calories: 380, protein: 7,   carbs: 55,   fat: 16,   tags: ['ladoo','laddoo','besan','dessert','indian'] },

  /* ========== CHINESE ========== */
  { name: 'Fried rice (egg)',                 calories: 163, protein: 4.5, carbs: 26,   fat: 5,    tags: ['fried','rice','egg','chinese'] },
  { name: 'Noodles, boiled',                  calories: 138, protein: 4.5, carbs: 28,   fat: 0.9,  tags: ['noodles','chinese'] },
  { name: 'Chow mein',                        calories: 175, protein: 7,   carbs: 25,   fat: 6,    tags: ['chow','mein','noodles','chinese'] },
  { name: 'Dim sum, pork dumpling',           calories: 80,  protein: 5,   carbs: 7,    fat: 3,    tags: ['dim sum','dumpling','pork','chinese'] },
  { name: 'Spring roll (fried)',              calories: 220, protein: 5,   carbs: 24,   fat: 12,   tags: ['spring','roll','fried','chinese'] },
  { name: 'Kung pao chicken',                 calories: 185, protein: 18,  carbs: 8,    fat: 9,    tags: ['kung','pao','chicken','chinese'] },
  { name: 'Sweet and sour pork',              calories: 210, protein: 14,  carbs: 22,   fat: 8,    tags: ['sweet','sour','pork','chinese'] },
  { name: 'Mapo tofu',                        calories: 110, protein: 7,   carbs: 6,    fat: 7,    tags: ['mapo','tofu','chinese'] },
  { name: 'Hot and sour soup',                calories: 70,  protein: 4,   carbs: 8,    fat: 2.5,  tags: ['hot','sour','soup','chinese'] },
  { name: 'Wonton soup',                      calories: 75,  protein: 5,   carbs: 8,    fat: 2,    tags: ['wonton','soup','chinese'] },
  { name: 'Peking duck',                      calories: 339, protein: 19,  carbs: 0,    fat: 29,   tags: ['peking','duck','chinese'] },
  { name: 'General Tso chicken',              calories: 296, protein: 22,  carbs: 25,   fat: 11,   tags: ['general','tso','chicken','chinese'] },
  { name: 'Egg drop soup',                    calories: 65,  protein: 4,   carbs: 7,    fat: 2,    tags: ['egg','drop','soup','chinese'] },
  { name: 'Sesame noodles',                   calories: 210, protein: 6,   carbs: 30,   fat: 8,    tags: ['sesame','noodles','chinese'] },
  { name: 'Bok choy (cooked)',                calories: 21,  protein: 2.5, carbs: 3,    fat: 0.3,  tags: ['bok','choy','vegetable','chinese'] },
  { name: 'Tofu, silken',                     calories: 55,  protein: 5,   carbs: 2,    fat: 3,    tags: ['tofu','silken','chinese','vegan'] },
  { name: 'Lo mein',                          calories: 180, protein: 7,   carbs: 26,   fat: 6,    tags: ['lo','mein','noodles','chinese'] },
  { name: 'Congee (rice porridge)',           calories: 65,  protein: 1.5, carbs: 14,   fat: 0.2,  tags: ['congee','rice','porridge','chinese'] },
  { name: 'Soy sauce',                        calories: 53,  protein: 8,   carbs: 5,    fat: 0.1,  tags: ['soy','sauce','condiment','chinese'] },
  { name: 'Sesame oil',                       calories: 884, protein: 0,   carbs: 0,    fat: 100,  tags: ['sesame','oil','fat','chinese'] },

  /* ========== ARAB / MIDDLE EASTERN ========== */
  { name: 'Hummus',                           calories: 166, protein: 8,   carbs: 14,   fat: 10,   tags: ['hummus','arab','middle eastern','dip'] },
  { name: 'Falafel (fried)',                  calories: 333, protein: 13,  carbs: 32,   fat: 18,   tags: ['falafel','arab','middle eastern'] },
  { name: 'Shawarma, chicken',                calories: 215, protein: 20,  carbs: 15,   fat: 8,    tags: ['shawarma','chicken','arab','middle eastern'] },
  { name: 'Shawarma, lamb',                   calories: 260, protein: 18,  carbs: 15,   fat: 13,   tags: ['shawarma','lamb','arab','middle eastern'] },
  { name: 'Kebab, lamb',                      calories: 235, protein: 20,  carbs: 2,    fat: 16,   tags: ['kebab','lamb','arab','middle eastern'] },
  { name: 'Kebab, chicken',                   calories: 180, protein: 22,  carbs: 2,    fat: 9,    tags: ['kebab','chicken','arab','middle eastern'] },
  { name: 'Tabouleh',                         calories: 90,  protein: 2.5, carbs: 13,   fat: 4,    tags: ['tabouleh','salad','arab','middle eastern'] },
  { name: 'Fattoush salad',                   calories: 80,  protein: 2,   carbs: 12,   fat: 3,    tags: ['fattoush','salad','arab','middle eastern'] },
  { name: 'Baba ganoush',                     calories: 90,  protein: 2,   carbs: 8,    fat: 6,    tags: ['baba','ganoush','eggplant','arab','middle eastern'] },
  { name: 'Pita bread',                       calories: 275, protein: 9,   carbs: 55,   fat: 1.5,  tags: ['pita','bread','arab','middle eastern'] },
  { name: 'Mansaf (lamb & rice)',             calories: 290, protein: 18,  carbs: 28,   fat: 11,   tags: ['mansaf','lamb','rice','arab','jordanian'] },
  { name: 'Mujaddara (lentil rice)',          calories: 150, protein: 6,   carbs: 27,   fat: 3,    tags: ['mujaddara','lentil','rice','arab','middle eastern'] },
  { name: 'Dolma (stuffed grape leaves)',     calories: 100, protein: 2.5, carbs: 12,   fat: 5,    tags: ['dolma','stuffed','grape','leaves','arab','middle eastern'] },
  { name: 'Kibbeh (baked)',                   calories: 218, protein: 14,  carbs: 18,   fat: 10,   tags: ['kibbeh','lamb','arab','middle eastern'] },
  { name: 'Baklava',                          calories: 428, protein: 5,   carbs: 52,   fat: 23,   tags: ['baklava','pastry','dessert','arab','middle eastern'] },
  { name: 'Dates',                            calories: 277, protein: 1.8, carbs: 75,   fat: 0.2,  tags: ['dates','fruit','arab','middle eastern'] },
  { name: 'Tahini',                           calories: 595, protein: 17,  carbs: 21,   fat: 54,   tags: ['tahini','sesame','paste','arab','middle eastern'] },
  { name: 'Halloumi cheese (grilled)',        calories: 319, protein: 21,  carbs: 1,    fat: 26,   tags: ['halloumi','cheese','arab','middle eastern'] },
  { name: 'Turkish delight',                  calories: 322, protein: 0.4, carbs: 81,   fat: 0.1,  tags: ['turkish','delight','sweet','dessert','arab','middle eastern'] },
  { name: 'Labneh (strained yogurt)',         calories: 130, protein: 7,   carbs: 4,    fat: 10,   tags: ['labneh','yogurt','arab','middle eastern'] },

  /* ========== EUROPEAN ========== */
  { name: 'Pasta, spaghetti (cooked)',        calories: 131, protein: 5,   carbs: 25,   fat: 1.1,  tags: ['pasta','spaghetti','italian','european'] },
  { name: 'Pasta, penne (cooked)',            calories: 131, protein: 5,   carbs: 25,   fat: 1.1,  tags: ['pasta','penne','italian','european'] },
  { name: 'Pizza, margherita (1 slice)',      calories: 200, protein: 8,   carbs: 25,   fat: 8,    tags: ['pizza','margherita','italian','european'] },
  { name: 'Pizza, pepperoni (1 slice)',       calories: 260, protein: 11,  carbs: 25,   fat: 13,   tags: ['pizza','pepperoni','italian','european'] },
  { name: 'Risotto (plain)',                  calories: 145, protein: 3.5, carbs: 26,   fat: 3.5,  tags: ['risotto','rice','italian','european'] },
  { name: 'Lasagna (meat)',                   calories: 185, protein: 11,  carbs: 16,   fat: 8,    tags: ['lasagna','pasta','italian','european'] },
  { name: 'Carbonara pasta',                  calories: 220, protein: 10,  carbs: 26,   fat: 9,    tags: ['carbonara','pasta','italian','european'] },
  { name: 'Bolognese (beef ragu)',            calories: 165, protein: 12,  carbs: 8,    fat: 9,    tags: ['bolognese','beef','pasta','italian','european'] },
  { name: 'Tiramisu',                         calories: 240, protein: 5,   carbs: 28,   fat: 12,   tags: ['tiramisu','dessert','italian','european'] },
  { name: 'Croissant',                        calories: 406, protein: 8,   carbs: 46,   fat: 21,   tags: ['croissant','pastry','french','european'] },
  { name: 'Baguette',                         calories: 270, protein: 9,   carbs: 55,   fat: 1.5,  tags: ['baguette','bread','french','european'] },
  { name: 'French onion soup',                calories: 95,  protein: 4,   carbs: 12,   fat: 3.5,  tags: ['french','onion','soup','european'] },
  { name: 'Crepe (plain)',                    calories: 205, protein: 6,   carbs: 30,   fat: 7,    tags: ['crepe','french','european'] },
  { name: 'Quiche lorraine (1 slice)',        calories: 330, protein: 11,  carbs: 22,   fat: 22,   tags: ['quiche','french','european'] },
  { name: 'Ratatouille',                      calories: 70,  protein: 2,   carbs: 10,   fat: 3,    tags: ['ratatouille','vegetable','french','european'] },
  { name: 'Beef steak (grilled)',             calories: 217, protein: 26,  carbs: 0,    fat: 12,   tags: ['steak','beef','european','american'] },
  { name: 'Fish and chips',                   calories: 290, protein: 16,  carbs: 28,   fat: 13,   tags: ['fish','chips','british','european'] },
  { name: 'Shepherd pie',                     calories: 170, protein: 10,  carbs: 16,   fat: 7,    tags: ['shepherd','pie','british','european'] },
  { name: 'Full English breakfast',           calories: 560, protein: 30,  carbs: 30,   fat: 33,   tags: ['english','breakfast','british','european'] },
  { name: 'Bratwurst sausage',                calories: 333, protein: 12,  carbs: 3,    fat: 30,   tags: ['bratwurst','sausage','german','european'] },
  { name: 'Sauerkraut',                       calories: 19,  protein: 0.9, carbs: 4.3,  fat: 0.1,  tags: ['sauerkraut','cabbage','german','european'] },
  { name: 'Pretzel',                          calories: 380, protein: 10,  carbs: 78,   fat: 2,    tags: ['pretzel','bread','german','european'] },
  { name: 'Schnitzel (pork)',                 calories: 280, protein: 22,  carbs: 14,   fat: 15,   tags: ['schnitzel','pork','german','austrian','european'] },
  { name: 'Paella (seafood)',                 calories: 180, protein: 12,  carbs: 22,   fat: 5,    tags: ['paella','seafood','rice','spanish','european'] },
  { name: 'Churros',                          calories: 440, protein: 5,   carbs: 55,   fat: 22,   tags: ['churros','pastry','dessert','spanish','european'] },
  { name: 'Gazpacho',                         calories: 45,  protein: 1.5, carbs: 7,    fat: 1.5,  tags: ['gazpacho','soup','spanish','european'] },
  { name: 'Meatballs, Swedish',               calories: 227, protein: 14,  carbs: 8,    fat: 16,   tags: ['meatballs','swedish','european'] },
  { name: 'Greek salad',                      calories: 100, protein: 3.5, carbs: 7,    fat: 7,    tags: ['greek','salad','european','mediterranean'] },
  { name: 'Moussaka',                         calories: 190, protein: 11,  carbs: 12,   fat: 11,   tags: ['moussaka','greek','european'] },

  /* ========== AMERICAN ========== */
  { name: 'Burger (beef, plain)',             calories: 295, protein: 17,  carbs: 24,   fat: 14,   tags: ['burger','beef','american'] },
  { name: 'Cheeseburger',                     calories: 350, protein: 20,  carbs: 25,   fat: 18,   tags: ['cheeseburger','burger','american'] },
  { name: 'Hot dog (with bun)',               calories: 290, protein: 11,  carbs: 23,   fat: 17,   tags: ['hot','dog','sausage','american'] },
  { name: 'French fries (medium)',            calories: 365, protein: 4,   carbs: 48,   fat: 17,   tags: ['fries','chips','potato','american'] },
  { name: 'Mac and cheese',                   calories: 172, protein: 6.5, carbs: 23,   fat: 6,    tags: ['mac','cheese','macaroni','american'] },
  { name: 'Pancakes (plain)',                 calories: 227, protein: 6,   carbs: 38,   fat: 7,    tags: ['pancakes','breakfast','american'] },
  { name: 'Waffles',                          calories: 291, protein: 8,   carbs: 37,   fat: 13,   tags: ['waffles','breakfast','american'] },
  { name: 'Bagel (plain)',                    calories: 270, protein: 10,  carbs: 53,   fat: 1.5,  tags: ['bagel','bread','american'] },
  { name: 'Cream cheese',                     calories: 342, protein: 6,   carbs: 4.1,  fat: 34,   tags: ['cream','cheese','american'] },
  { name: 'Buffalo wings',                    calories: 320, protein: 26,  carbs: 7,    fat: 21,   tags: ['buffalo','wings','chicken','american'] },
  { name: 'BBQ ribs (pork)',                  calories: 290, protein: 21,  carbs: 10,   fat: 19,   tags: ['bbq','ribs','pork','american'] },
  { name: 'Pulled pork',                      calories: 240, protein: 20,  carbs: 9,    fat: 14,   tags: ['pulled','pork','bbq','american'] },
  { name: 'Clam chowder',                     calories: 130, protein: 7,   carbs: 13,   fat: 6,    tags: ['clam','chowder','soup','american'] },
  { name: 'Caesar salad',                     calories: 140, protein: 5,   carbs: 8,    fat: 10,   tags: ['caesar','salad','american'] },
  { name: 'Coleslaw',                         calories: 150, protein: 1.5, carbs: 14,   fat: 10,   tags: ['coleslaw','salad','american'] },
  { name: 'Cornbread',                        calories: 198, protein: 4,   carbs: 29,   fat: 8,    tags: ['cornbread','bread','american'] },
  { name: 'Brownie (chocolate)',              calories: 415, protein: 5,   carbs: 63,   fat: 17,   tags: ['brownie','chocolate','dessert','american'] },
  { name: 'Cheesecake (plain)',               calories: 321, protein: 6,   carbs: 25,   fat: 23,   tags: ['cheesecake','dessert','american'] },
  { name: 'Apple pie (1 slice)',              calories: 296, protein: 2.5, carbs: 43,   fat: 13,   tags: ['apple','pie','dessert','american'] },
  { name: 'Donut (glazed)',                   calories: 452, protein: 5,   carbs: 51,   fat: 25,   tags: ['donut','doughnut','dessert','american'] },
  { name: 'Peanut butter sandwich',           calories: 380, protein: 14,  carbs: 42,   fat: 18,   tags: ['peanut','butter','sandwich','american'] },
  { name: 'BLT sandwich',                     calories: 350, protein: 16,  carbs: 32,   fat: 18,   tags: ['blt','bacon','sandwich','american'] },
  { name: 'Grilled cheese sandwich',          calories: 391, protein: 16,  carbs: 32,   fat: 23,   tags: ['grilled','cheese','sandwich','american'] },
  { name: 'Fried chicken (1 piece)',          calories: 320, protein: 22,  carbs: 14,   fat: 20,   tags: ['fried','chicken','american'] },
  { name: 'Corn on the cob',                  calories: 96,  protein: 3.4, carbs: 21,   fat: 1.5,  tags: ['corn','cob','american'] },
  { name: 'Baked beans',                      calories: 155, protein: 8,   carbs: 28,   fat: 1.5,  tags: ['baked','beans','american'] },
  { name: 'Nachos with cheese',               calories: 346, protein: 9,   carbs: 35,   fat: 19,   tags: ['nachos','cheese','american','mexican'] },
  { name: 'Burrito (chicken)',                calories: 310, protein: 18,  carbs: 38,   fat: 9,    tags: ['burrito','chicken','mexican','american'] },
  { name: 'Taco (beef)',                      calories: 210, protein: 12,  carbs: 18,   fat: 10,   tags: ['taco','beef','mexican','american'] },
  { name: 'Quesadilla (cheese)',              calories: 370, protein: 16,  carbs: 35,   fat: 18,   tags: ['quesadilla','cheese','mexican','american'] },
  { name: 'Guacamole',                        calories: 150, protein: 2,   carbs: 8,    fat: 13,   tags: ['guacamole','avocado','mexican','american'] },
  { name: 'Salsa',                            calories: 36,  protein: 1.5, carbs: 7,    fat: 0.3,  tags: ['salsa','sauce','mexican','american'] },

  /* ========== COMMON PROTEINS ========== */
  { name: 'Chicken breast (cooked)',          calories: 165, protein: 31,  carbs: 0,    fat: 3.6,  tags: ['chicken','breast','poultry','meat'] },
  { name: 'Chicken thigh (cooked)',           calories: 229, protein: 25,  carbs: 0,    fat: 14,   tags: ['chicken','thigh','poultry','meat'] },
  { name: 'Ground beef 85/15 (cooked)',       calories: 250, protein: 26,  carbs: 0,    fat: 15,   tags: ['beef','ground','meat','mince'] },
  { name: 'Sirloin steak (cooked)',           calories: 201, protein: 29,  carbs: 0,    fat: 9,    tags: ['beef','steak','sirloin','meat'] },
  { name: 'Salmon (cooked)',                  calories: 208, protein: 20,  carbs: 0,    fat: 13,   tags: ['salmon','fish','seafood'] },
  { name: 'Tuna, canned',                     calories: 116, protein: 25,  carbs: 0,    fat: 1,    tags: ['tuna','fish','seafood'] },
  { name: 'Egg, whole',                       calories: 143, protein: 13,  carbs: 1,    fat: 10,   tags: ['egg','eggs'] },
  { name: 'Egg white',                        calories: 52,  protein: 11,  carbs: 0.7,  fat: 0.2,  tags: ['egg','white','eggs'] },
  { name: 'Whey protein powder',              calories: 400, protein: 80,  carbs: 8,    fat: 5,    tags: ['whey','protein','supplement','powder'] },
  { name: 'Casein protein powder',            calories: 370, protein: 75,  carbs: 10,   fat: 4,    tags: ['casein','protein','supplement','powder'] },

  /* ========== COMMON CARBS ========== */
  { name: 'Rice, white (cooked)',             calories: 130, protein: 2.7, carbs: 28,   fat: 0.3,  tags: ['rice','white','grain'] },
  { name: 'Rice, brown (cooked)',             calories: 123, protein: 2.7, carbs: 26,   fat: 1,    tags: ['rice','brown','grain'] },
  { name: 'Oats, rolled (dry)',               calories: 389, protein: 17,  carbs: 66,   fat: 7,    tags: ['oats','oatmeal','porridge','grain'] },
  { name: 'Sweet potato (baked)',             calories: 90,  protein: 2,   carbs: 21,   fat: 0.2,  tags: ['sweet','potato','vegetable'] },
  { name: 'Banana',                           calories: 89,  protein: 1.1, carbs: 23,   fat: 0.3,  tags: ['banana','fruit'] },
  { name: 'Bread, whole wheat',               calories: 247, protein: 13,  carbs: 41,   fat: 3.5,  tags: ['bread','wheat','grain'] },
  { name: 'Quinoa (cooked)',                  calories: 120, protein: 4.4, carbs: 21,   fat: 1.9,  tags: ['quinoa','grain'] },

  /* ========== COMMON FATS ========== */
  { name: 'Avocado',                          calories: 160, protein: 2,   carbs: 9,    fat: 15,   tags: ['avocado','fruit','fat'] },
  { name: 'Almonds',                          calories: 579, protein: 21,  carbs: 22,   fat: 50,   tags: ['almond','nut','nuts'] },
  { name: 'Peanut butter',                    calories: 588, protein: 25,  carbs: 20,   fat: 50,   tags: ['peanut','butter','nut'] },
  { name: 'Olive oil',                        calories: 884, protein: 0,   carbs: 0,    fat: 100,  tags: ['olive','oil','fat'] },
  { name: 'Walnuts',                          calories: 654, protein: 15,  carbs: 14,   fat: 65,   tags: ['walnut','nut','nuts'] },
  { name: 'Chia seeds',                       calories: 486, protein: 17,  carbs: 42,   fat: 31,   tags: ['chia','seeds'] },

  /* ========== DAIRY ========== */
  { name: 'Greek yogurt (nonfat)',            calories: 59,  protein: 10,  carbs: 3.6,  fat: 0.4,  tags: ['yogurt','greek','dairy'] },
  { name: 'Milk, whole',                      calories: 61,  protein: 3.2, carbs: 4.8,  fat: 3.3,  tags: ['milk','dairy'] },
  { name: 'Cheddar cheese',                   calories: 404, protein: 23,  carbs: 3.4,  fat: 33,   tags: ['cheese','cheddar','dairy'] },
  { name: 'Cottage cheese',                   calories: 81,  protein: 11,  carbs: 3.4,  fat: 2.3,  tags: ['cottage','cheese','dairy'] },

  /* ========== DRINKS ========== */
  { name: 'Orange juice (fresh)',             calories: 45,  protein: 0.7, carbs: 10,   fat: 0.2,  tags: ['orange','juice','drink'] },
  { name: 'Coconut water',                    calories: 19,  protein: 0.7, carbs: 3.7,  fat: 0.2,  tags: ['coconut','water','drink'] },
  { name: 'Whole milk',                       calories: 61,  protein: 3.2, carbs: 4.8,  fat: 3.3,  tags: ['milk','whole','drink','dairy'] },
  { name: 'Coffee, black',                    calories: 2,   protein: 0.1, carbs: 0,    fat: 0,    tags: ['coffee','drink','beverage'] },
  { name: 'Green tea',                        calories: 1,   protein: 0,   carbs: 0.2,  fat: 0,    tags: ['green','tea','drink','beverage'] },
  { name: 'Protein shake (milk based)',       calories: 180, protein: 25,  carbs: 12,   fat: 4,    tags: ['protein','shake','supplement','drink'] }

];

/* Attach a stable id + brand so local entries share the same shape as API.
   Note: values marked "USDA" are USDA-derived; cultural dishes are researched
   cuisine averages kept under the same brand field for card rendering. */
export const FOODS_DB = RAW_FOODS.map((f, i) => ({
  ...f,
  id:    'local_' + i,
  brand: f.tags.includes('bangladeshi') || f.tags.includes('indian') ||
         f.tags.includes('chinese') || f.tags.includes('arab') ||
         f.tags.includes('european') || f.tags.includes('american')
    ? 'Curated'
    : 'USDA'
}));
